-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS book_store.authors
(
    author_id integer NOT NULL,
    author_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    birth_date date,
    nationality character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT authors_pkey PRIMARY KEY (author_id)
);

CREATE TABLE IF NOT EXISTS book_store.book_authors
(
    id serial NOT NULL,
    book_id integer,
    author_id integer,
    CONSTRAINT book_authors_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS book_store.books
(
    book_id serial NOT NULL,
    author character varying(50) COLLATE pg_catalog."default" NOT NULL,
    genre character varying(50) COLLATE pg_catalog."default",
    publisher_id integer NOT NULL,
    publication_year integer,
    CONSTRAINT books_pkey PRIMARY KEY (book_id)
);

CREATE TABLE IF NOT EXISTS book_store.customers
(
    customer_id integer NOT NULL,
    customer_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default",
    address character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT customers_pkey PRIMARY KEY (customer_id),
    CONSTRAINT customers_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS book_store.order_items
(
    id serial NOT NULL,
    order_id integer,
    book_id integer,
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS book_store.orders
(
    order_id integer NOT NULL,
    order_date timestamp without time zone DEFAULT now(),
    customer_id integer,
    total_amount integer,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS book_store.publishers
(
    publisher_id integer NOT NULL,
    publisher_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    country character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT publishers_pkey PRIMARY KEY (publisher_id)
);

ALTER TABLE IF EXISTS book_store.book_authors
    ADD CONSTRAINT book_authors_author_id_fkey FOREIGN KEY (author_id)
    REFERENCES book_store.authors (author_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS book_store.book_authors
    ADD CONSTRAINT book_authors_book_id_fkey FOREIGN KEY (book_id)
    REFERENCES book_store.books (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS book_store.books
    ADD CONSTRAINT books_publisher_id_fkey FOREIGN KEY (publisher_id)
    REFERENCES book_store.publishers (publisher_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS book_store.order_items
    ADD CONSTRAINT order_items_book_id_fkey FOREIGN KEY (book_id)
    REFERENCES book_store.books (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS book_store.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES book_store.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS book_store.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES book_store.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;